### ISSUE TITLE
Веб сокеты

### ISSUE THREAD

**Issue by Nivanchenko** [autumn-library/winow#22]
рассмотреть возможность реализовать

**Comment by Nivanchenko** [comment]
рабочий пример тут https://github.com/Nivanchenko/oscript-tcp-issue-example
Нужно победить шифрование фреймов, и как-то заархитектурить оброботку таких соедиений

**Comment by vasvl123** [comment]
TCPСоединение Соединение = Задача.Соединение;

								var ПС = Символы.ВК + Символы.ПС;
								var дРезультат = Новый.Массив();
								if (!Задача.Свойство("Заголовки"))
								{
									дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("HTTP/1.1 101 Switching Protocols" + ПС));
									дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Upgrade: websocket" + ПС));
									дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Connection: Upgrade" + ПС));
									дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Sec-WebSocket-Accept: " + ГенерацияХешаОтвета((string)Задача.Заголовок.Получить("Sec-WebSocket-Key")) + ПС + ПС));
									Соединение.ОтправитьДвоичныеДанныеАсинхронно(СоединитьДвоичныеДанные(дРезультат));
									Задача.Вставить("Заголовки", "");
									дРезультат.Очистить();
									Соединение.upgrade("socket");
									Соединения.Добавить(Соединение);

								}

								var Кусок = Задача.Результат as ДвоичныеДанные;

								var Length = Кусок.Размер();

								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(0x80 | 0x01) }));

								if (Length <= 125)
									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(Length & 0xFF) }));
								else if (Length <= 65535)
								{
									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(126) }));
									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)((Length >> 8) & 0xFF) }));
									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(Length & 0xFF) }));
								}
								else
								{
									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(127) }));
									for (int i = 7; i >= 0; i--)
										дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)((Length >> (8 * i)) & 0xFF) }));
								}

								дРезультат.Добавить(Кусок);

								Соединение.ОтправитьДвоичныеДанныеАсинхронно(СоединитьДвоичныеДанные(дРезультат));

								Задача.Результат = Неопределено;
``

**Comment by Nivanchenko** [comment]
> ```
> 							TCPСоединение Соединение = Задача.Соединение;
> 
> 							var ПС = Символы.ВК + Символы.ПС;
> 							var дРезультат = Новый.Массив();
> 							if (!Задача.Свойство("Заголовки"))
> 							{
> 								дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("HTTP/1.1 101 Switching Protocols" + ПС));
> 								дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Upgrade: websocket" + ПС));
> 								дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Connection: Upgrade" + ПС));
> 								дРезультат.Добавить(ПолучитьДвоичныеДанныеИзСтроки("Sec-WebSocket-Accept: " + ГенерацияХешаОтвета((string)Задача.Заголовок.Получить("Sec-WebSocket-Key")) + ПС + ПС));
> 								Соединение.ОтправитьДвоичныеДанныеАсинхронно(СоединитьДвоичныеДанные(дРезультат));
> 								Задача.Вставить("Заголовки", "");
> 								дРезультат.Очистить();
> 								Соединение.upgrade("socket");
> 								Соединения.Добавить(Соединение);
> 
> 							}
> 
> 							var Кусок = Задача.Результат as ДвоичныеДанные;
> 
> 							var Length = Кусок.Размер();
> 
> 							дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(0x80 | 0x01) }));
> 
> 							if (Length <= 125)
> 								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(Length & 0xFF) }));
> 							else if (Length <= 65535)
> 							{
> 								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(126) }));
> 								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)((Length >> 8) & 0xFF) }));
> 								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(Length & 0xFF) }));
> 							}
> 							else
> 							{
> 								дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)(127) }));
> 								for (int i = 7; i >= 0; i--)
> 									дРезультат.Добавить(new ДвоичныеДанные(new byte[] { (byte)((Length >> (8 * i)) & 0xFF) }));
> 							}
> 
> 							дРезультат.Добавить(Кусок);
> 
> 							Соединение.ОтправитьДвоичныеДанныеАсинхронно(СоединитьДвоичныеДанные(дРезультат));
> 
> 							Задача.Результат = Неопределено;
> ```
> 
> ``

Спасибо!

**Comment by Nivanchenko** [comment]
Наконец то, экспериментально заработало https://github.com/autumn-library/winow/pull/45
