### ISSUE TITLE
Хочется увидеть в документации, где хранить настройки веб-приложения, как к ним обращаться?

### ISSUE THREAD

**Issue by artbear** [autumn-library/winow#40]
- часть настроек хранить в файле настроек
- а часть настроек можно брать из переменных окружения

**Comment by Nivanchenko** [comment]
В документации уточню.
По быстрому в целом суть в том, что в каталоге запуска скрипта должен лежать либо [autumn-properties.json](https://github.com/autumn-library/winow/blob/master/autumn-properties.json) либо autumn-properties.yaml. Настройки прилетят в этот [объект](https://github.com/autumn-library/winow/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8.os). Его можно внедрить в любое место, [например](https://github.com/autumn-library/winow/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A1%D0%BB%D1%83%D1%88%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%9F%D0%BE%D1%80%D1%82%D0%B0.os#L15).

[Вот дока в осени](https://github.com/autumn-library/autumn#%D0%B2%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BA-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)

**Comment by artbear** [comment]
Выполнено. Закрываю.
