### ISSUE TITLE
Документация - как запускать в докере и передавать параметры приложению

### ISSUE THREAD

**Issue by artbear** [autumn-library/winow#41]

**Comment by Nivanchenko** [comment]
[Упомянул](https://github.com/autumn-library/winow#%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F) в инструкции, и [добавил пример](https://github.com/autumn-library/winow/tree/master/docker) приложения с описанием докер файла.

**Comment by artbear** [comment]
Выполнено. закрываю.
