### ISSUE TITLE
Возможна ли авторизация по ad?

### ISSUE THREAD

**Issue by kuzyara** [autumn-library/winow#47]
Возможна ли авторизация по active directory?

Как в 1с

**Comment by Nivanchenko** [comment]
Привет. Нет, на текущий момент возможна только basic авторизация. В планах есть разработка других способов, но в ближайшее время точно не будет. Если нужна авторизация через ad, но без разделения доступов по ролям, т.е. просто пускать\не пускать в приложение, то можно winow спрятать за iis, apache, nginx. Которые умеют в такую авторизацию.

**Comment by kuzyara** [comment]
спасибо, закрываю
