### ISSUE TITLE
Пластилин в точки маршрута

### ISSUE THREAD

**Issue by Absolemus** [autumn-library/winow#50]
Предусмотреть возможность добавления желудей в параметры точек машрутов

```bsl
&ТочкаМаршрута("/")
Процедура МойМаршрут(Запрос, Ответ, &Пластилин МойОбъект) Экспорт
```

Не могу определить желудь в переменных объекта, потому что нужен желудь с характером Компанейский, а тут у нас контроллер создается всего раз, и который желудь к нему прикрепился, тот и будет использоваться постоянно.

В моем случае мне надо заполнять некоторые желуди данными, которые прилетают извне. И желудь всегда должен быть новым (т.е. пустым)

**Comment by Absolemus** [comment]
Я у тебя украл технологию, по который ты работаешь с маршрутами и сделал вот таким образом установку произвольных желудей в параметры метода

[Ссылочка](https://github.com/Absolemus/autumn-telegram/blob/f03b6ac251f2e3281706e4d34f0fa7658b2555eb/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9E%D1%80%D0%BA%D0%B5%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B/%D0%9E%D1%80%D0%BA%D0%B5%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%A1%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9.os#L72)


Может конечно не очень красиво тащить поделку в желудь, но другого я ничего не придумал

**Comment by Nivanchenko** [comment]
Мне кажется, тебе очень зайдет [табакерка](https://github.com/autumn-library/autumn#%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%BE%D0%B2-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2). Его можно внедрить в поле класса, и из него "доставать" при необходимости.
