### ISSUE TITLE
Пример загрузке файла. При пустой дате падает с ошибкой

### ISSUE THREAD

**Issue by GenVP** [autumn-library/winow#58]
Если для примера "ОтправкаФайлов.os" перед нажатием "Upload" не заполнить дату, то код упадет с ошибкой
"{Модуль C:\OneScript\lib\winow\src\Классы\ДанныеСоставнойФормы.os / Ошибка в строке: 55 / Внешнее исключение (System.NullReferenceException): Ссылка на объект не указывает на экземпляр объекта.} "

Из-за `Результат.Значение = Неопределено`
![изображение](https://github.com/autumn-library/winow/assets/34754769/cd30bb6b-d04e-45b2-b600-2dcd1682c6cc)

Это ошибка winow или как-то нужно делать проверку заполнения даты?

**Comment by Nivanchenko** [comment]
Поправил. https://github.com/autumn-library/winow/commit/c5beda29a426cfaa4eaeab651c9e0c607a5c9732
