### ISSUE TITLE
Зависание приложения при получении POST запроса

### ISSUE THREAD

**Issue by abirambul** [autumn-library/winow#71]
Обновил winow до 0.8.0 в своем приложении.

У меня была проблема с POST запросами в которых передаются ДД размером более 9 Мб (примерно). Данные приходили неполные и разрывало соединение некорректно (Error: read ECONNRESET). Причем с запросами только с других машин, т.е. с localhost,IP или по имени локальной машины работало без ошибок.

После обновления с 0.7.0 на 0.8.0 получил зависание приложения при получении POST запросов. При этом oscript.exe постоянно отъедает процессор.

Зависает на строке [`Соединение.ПрочитатьДвоичныеДанные(РазмерБуфера)`](https://github.com/autumn-library/winow/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%A1%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9.os#L56).
Если указать РазмерБуфера = 0 [тут](https://github.com/autumn-library/winow/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%A1%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9.os#L13), то работает корректно - файл приходит в полном размере и без разрыва соединения.

Возможно, что в [коде](https://github.com/EvilBeaver/OneScript/blob/9ce002f52f43f71039df767f6f7c00e4a9bc8cad/src/OneScript.StandardLibrary/Net/TCPClient.cs#L70-L92) oscript есть ошибка.

Может в детальки `РазмерБуфера` стоит добавить?

**Comment by Nivanchenko** [comment]
Да, давай сделаем детальку. Хороший анализ. Спасибо!

**Comment by Nivanchenko** [comment]
Решено в https://github.com/autumn-library/winow/releases/tag/v0.8.1
